version: "3.7"
services:
  customerapplication:
    build: .
    restart: on-failure:1
    ports:
      - 8070:8080
    depends_on:
      - mysql_db
    links:
      - mysql_db:app_db
  mysql_db:
    image: "mariadb:latest"
    restart: on-failure:5
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: transaction
      MYSQL_USER: java_to_dev
      MYSQL_PASSWORD: nE5kMc7JCGNqwDQM
      MYSQL_ROOT_PASSWORD: root